"""create chat conversations

Revision ID: b54c5af2a65c
Revises: e0a9a2a809ff
Create Date: 2026-09-06 04:01:14.761627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54c5af2a65c'
down_revision: Union[str, Sequence[str], None] = 'e0a9a2a809ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_created_at'), 'chat_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_conversations_id'), 'chat_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.add_column('chat_messages', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('chat_messages_user_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_conversations', ['conversation_id'], ['id'])
    op.drop_column('chat_messages', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_user_id_fkey'), 'chat_messages', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.drop_column('chat_messages', 'conversation_id')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_created_at'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
